# 集群配置
brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
# 文件清理
deleteWhen = 04
fileReservedTime = 72
# 角色与性能
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH
# 本地开发可开启自动创建
autoCreateTopicEnable = true
# 关键：设置为宿主机在 Docker 网络中的网关 IP
# brokerIP1 = 192.168.1.176